### ISSUE TITLE
Missing text on particular xml

### ISSUE THREAD

**Issue by ades4827** [clearstream/xml-to-array#3]
Hi,
i using this package for an xml formatted in a particular way (perhaps not exactly standard) and I found a case in which some of the values ​​are not parsed. is it a bug or is it normal?

Below is the example to replicate the problem:

```
$xml = <<<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<quizzes>
    <quiz arg_1="1" arg_2="5" arg_3="6">
        <question>
            CUSTOM MISSING TEXT
            <img nome="image.jpg"></img>
        </question>
        <answer>answer</answer>
        <answer>answers</answer>
    </quiz>
</quizzes>
XML;

$array = XmlToArray::convert($xml);
dd($array['quizzes']['quiz'][0]['question'][0]['#text'] == '');
```

**Comment by trevorgehman** [comment]
Thanks for reporting! We'll take a look

**Comment by hivokas** [comment]
Thanks for reporting @ades4827!

Do you expect it to work like this? https://github.com/clearstream/xml-to-array/blob/602cd7a20b69878692306819ce6a67283b1453c5/tests/XmlToArrayConverterTest.php#L112-L145

**Comment by hivokas** [comment]
@ades4827 we've published a new `0.4.0` release which fixes this issue. Please upgrade the package and check if it works fine now.

**Comment by ades4827** [comment]
thank you very much, it works perfectly

**Comment by hivokas** [comment]
@ades4827 great, thanks again for reporting!
